from setuptools import setup, find_packages

setup(
    name="AITradeX",
    version="1.0.0",
    packages=find_packages(),
    install_requires=[
        "pandas>=1.5.0",
        "numpy>=1.21.0",
        "yfinance>=0.2.0",
        "scikit-learn>=1.0.0",
        "statsmodels>=0.13.0",
        "prophet>=1.1.0",
        "matplotlib>=3.5.0",
        "langchain>=0.1.0",
        "langchain-groq>=0.1.0",
        "python-dotenv>=0.19.0",
    ],
    author="Your Name",
    author_email="your.email@example.com",
    description="Advanced Stock Analysis System with AI-Powered Insights",
    long_description=open("README.md").read(),
    long_description_content_type="text/markdown",
    url="https://github.com/yourusername/AITradeX",
    classifiers=[
        "Development Status :: 4 - Beta",
        "Intended Audience :: Financial and Insurance Industry",
        "License :: OSI Approved :: MIT License",
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3.8",
        "Programming Language :: Python :: 3.9",
        "Programming Language :: Python :: 3.10",
        "Topic :: Office/Business :: Financial :: Investment",
    ],
    python_requires=">=3.8",
) 